config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'auth/google_oauth2', as: :sign_in_with_google
  get 'auth/google_oauth2/callback' => 'callbacks#google'
  get 'auth/facebook', as: :sign_in_with_facebook
  get 'auth/facebook/callback' => 'callbacks#facebook'

    root 'home#index'
    get '/about' => 'home#about', as: :about
    resources :posts do
      resources :comments
      resources :favourites, only: [:create, :destroy]
      resources :stars, only: [:create, :update, :destroy]
    end
    resources :users do
      get :edit, on: :collection
      patch :update, on: :collection
    end
    resources :sessions, only: [:new, :create] do
      delete :destroy, on: :collection
    end
    resources :password_resets
    resources :tags, only: [:index, :show]
end

app/models/favourite.rb
class Favourite < ApplicationRecord

  belongs_to :user
  belongs_to :post

  validates :post_id, presence: true, uniqueness: {scope: :user_id}
  validates :user_id, presence: true
  
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  before_action :authenticate_user

  def create
    @post = Post.find params[:post_id]
    @favourite = Favourite.new(user: current_user, post: @post)
    respond_to do |format|
    if cannot? :favourite, @post
      format.html { redirect_to :back, notice: "Access Denied" }
    elsif @favourite.save
      format.js { render :favourite_success }
      format.html { redirect_to :back, alert: 'Added to Favourites' }
    else
      format.html { redirect_to :back, alert: @favourite.errors.full_messages.join(", ") }
    end
  end
  end

  def destroy
    @favourite = Favourite.find params[:id]
    @post = @favourite.post
    respond_to do |format|
      if @favourite.destroy
        format.js { render :favourite_destroy }
        format.html { redirect_to :back, alert: 'Favourite Removed' }
      else
        format.html { redirect_to :back, alert: @favourite.errors.full_messages.join(", ") }
      end
    end
  end

end

app/views/favourites/_button.html.erb
<% if user_signed_in? && can?(:favourite, @post) %>
  <% if @favourite&.persisted? %>
    <%= link_to post_favourite_path(@post, @favourite),
    remote: true,
    method: :delete do %>
    <i class="fa fa-bookmark" aria-hidden="true"></i>
    <% end %>

  <% else %>
    <%= link_to post_favourites_path(@post),
    remote: true,
    method: :post do %>
    <i class="fa fa-bookmark-o" aria-hidden="true"></i>
    <% end %>
  <% end %>
<% end %>

app/views/favourites/favourite_destroy.js.erb
$('#favbutton').html('<%= j render 'button' %>');

app/views/favourites/favourite_success.js.erb
$('#favbutton').html('<%= j render 'button' %>');