config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'auth/google_oauth2', as: :sign_in_with_google
  get 'auth/google_oauth2/callback' => 'callbacks#google'
  get 'auth/facebook', as: :sign_in_with_facebook
  get 'auth/facebook/callback' => 'callbacks#facebook'

    root 'home#index'
    get '/about' => 'home#about', as: :about
    resources :posts do
      resources :comments
      resources :favourites, only: [:create, :destroy]
      resources :stars, only: [:create, :update, :destroy]
    end
    resources :users do
      get :edit, on: :collection
      patch :update, on: :collection
    end
    resources :sessions, only: [:new, :create] do
      delete :destroy, on: :collection
    end
    resources :password_resets
    resources :tags, only: [:index, :show]
end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :taggings, dependent: :destroy
  has_many :posts, through: :taggings

  validates :name, presence: true, uniqueness: { case_sensitive: false }
  
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tags = Tag.all.page(params[:page]).per(10)
  end

  def show
    @tags = Tag.find params[:id]
  end

end

app/views/tags/index.html.erb
<div class='form-container'>
  <% @tags.each do |t| %>
    <%= link_to t.name, tag_path(t) %> (<%= t.posts.size %> Posts) <br />
  <% end %>
</div>

  <%= paginate @tags %>

app/views/tags/show.html.erb
<h1>Posts by Tag: <%=@tags.name%></h1>

<% @tags.posts.each do |t| %>
<div class='index-element'>
  <div class='post-title'><%= link_to t.title, post_path(t) %></div>
  <div class='post-body'><%= t.body_snippet %></div>
</div>
<% end %>