config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'auth/google_oauth2', as: :sign_in_with_google
  get 'auth/google_oauth2/callback' => 'callbacks#google'
  get 'auth/facebook', as: :sign_in_with_facebook
  get 'auth/facebook/callback' => 'callbacks#facebook'

    root 'home#index'
    get '/about' => 'home#about', as: :about
    resources :posts do
      resources :comments
      resources :favourites, only: [:create, :destroy]
      resources :stars, only: [:create, :update, :destroy]
    end
    resources :users do
      get :edit, on: :collection
      patch :update, on: :collection
    end
    resources :sessions, only: [:new, :create] do
      delete :destroy, on: :collection
    end
    resources :password_resets
    resources :tags, only: [:index, :show]
end

app/models/post.rb
class Post < ApplicationRecord

  attr_accessor :facebook_post_this
  belongs_to :category
  belongs_to :user
  has_many :comments, lambda { order(created_at: :DESC) }, dependent: :destroy
  has_many :favourites, dependent: :destroy
  has_many :users_who_favored, through: :favourites, source: :user
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
  has_many :stars, dependent: :destroy
  has_many :starers

  validates :title, presence: true, length: { minimum: 7 },
            uniqueness: {case_sensitive: false, message: "must be unique"}
  validates :body, presence: true

  def body_snippet
    if self.body.length > 100
      return body[0...100] << "..."
    else
      return body
    end
  end

  def favourite_for(user)
    favourites.find_by(user: user)
  end

  def self.search(search)
    if search
      self.where('title ILIKE ? OR body ILIKE ?', "%#{search}%", "%#{search}%")
    else
      self.all
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user, except: [:index, :show]
  before_action :find_post, only: [:edit, :update, :destroy, :show]
  before_action :authorize_access, only: [:edit, :update, :destroy]
  before_action :set_page, only: [:index]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new find_params
    @post.user = current_user
    if @post.save
      if @post.facebook_post_this
        user_graph = Koala::Facebook::API.new(current_user.oauth_token)
        user_graph.put_wall_post("#{@post.title}: #{@post.body}")
      end
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @post = find_post
    @category = Category.find @post.category_id
    @favourite = @post.favourite_for(current_user)
    respond_to do |format|
      format.html {render}
      format.text {render}
      format.xml {render xml: @post.to_xml}
      format.json {render json: @post.to_json(include: [:category, :comments, :user])}
    end
  end


  def index
    @post = Post.search(params[:search]).order(created_at: :desc).
            includes(:category, :user).page(params[:page]).per(10)
    respond_to do |format|
        format.html {render}
        format.text {render}
        format.xml {render xml: @post.to_xml}
        format.json {render json: @post.to_json(include: [:category, :user])}
    end
  end

  def edit
    @post = find_post
  end

  def update
    @post = find_post
    if @post.update find_params
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post = find_post
    @post.destroy
    redirect_to posts_path
  end

  private

  def search
    search_query = params(:query)
    @query = Post.where(['title || body ILIKE ?', "#{search_query}"])
  end

  def set_page
    @page = params[:page] || 0
  end

  def authorize_access
    unless can? :modify, @post
      redirect_to root_path, alert: 'Access denied'
    end
  end

  def find_post
    @post ||= Post.find params[:id]
  end

  def find_params
    params.require(:post).permit([:title, :body, :facebook_post_this, :category_id, tag_ids: []])
  end

  def post_order
    order(created_at: :desc).includes(:category, :user).page(params[:page]).per(10)
  end

end

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= @post.errors.full_messages.join(', ') %>

<div class='form-container'>
  <%= form_for @post do |f| %>

    <div>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>

    <div>
      <%= f.label :body %>
      <%= f.text_area :body %>
    </div>

    <div>
      <%= f.label :category %>
      <%= f.collection_select :category_id, Category.all, :id, :title %>
    </div>

    <div>
      <%= f.label :tag %>
      <%= f.collection_select(:tag_ids, Tag.all, :id, :name, {}, { multiple: true, class: 'chosen-select'})%>
    </div>

    <%= f.submit %>

  <%end%>
</div>


<script>$('.chosen-select').chosen({ width: '90%'})</script>

app/views/posts/index.html.erb
<div id="index-container">
  <div id='index-search'>
    <%= form_tag posts_path, :method => 'get' do %>
        <%= text_field_tag :search, params[:search] %>
        <!-- <%= submit_tag 'Search', :name => nil %> -->
        <i class="fa fa-search" aria-hidden="true" id='form-submit-link'></i>
    <% end %>
    <%= button_to 'View by Tags', tags_path, :method => 'get' %>
</div>

  <% @post.each do |p| %>
  <div class='index-element'>
    <div class='post-title'><%= link_to p.title, post_path(p) %></div>
    <div class='post-body'><%= p.body_snippet %></div>
  </div>
  <% end %>


  <%= paginate @post %>
</div>

app/views/posts/new.html.erb
<%= @post.errors.full_messages.join(', ') %>

<div class='form-container'>
  <%= form_for @post do |f| %>
  
    <h1>New Post</h1>

    <div>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>

    <div>
      <%= f.label :body %>
      <%= f.text_area :body %>
    </div>

    <div>
      <%= f.label :category %>
      <%= f.collection_select(:category_id, Category.all, :id, :title, {}, { class: 'chosen-select'})%>
    </div>
    <div>
      <%= f.label :tag %>
      <%= f.collection_select(:tag_ids, Tag.all, :id, :name, {}, { multiple: true, class: 'chosen-select'})%>
    </div>

    <% if !@post.persisted? && current_user.signed_in_with_facebook? %>
      <div>
        <%= f.check_box :facebook_post_this %>
        <%= f.label :facebook_post_this %>
      </div>
    <% end %>

    <%= f.submit %>

  <%end%>
</div>

<script>$('.chosen-select').chosen({ width: '90%'})</script>

app/views/posts/show.html.erb
<h1 id='post-header'><%= @post.title %></h1>
  <div id= 'index-options'>
    <div id= 'favbutton'>
      <%= render '/favourites/button' %>
    </div>
    <% if can? :modify, @post %>
      <%= link_to edit_post_path(@post), method: :get do %>
      <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
      <% end %>
      <%= link_to post_path(@post),
      method: :delete,
      data: { confirm: 'Are you sure?' } do %>
      <i class="fa fa-trash" aria-hidden="true"></i>
      <% end %>
    <% end %>
  </div>

<div class="show-page">
  <div class="show-container">

    <p><%= @post.body %></p>
    <strong>Posted by:</strong> <%= @post.user_full_name %> <br />
    <strong>Category:</strong> <%= @post.category.title %> <br />
    <strong>Post Tags:</strong> <%= @post.tags.map(&:name).join(', ') %>

    <section class='star-widget'>
      <%= star_counter(@post) %>
      <% if @post.stars.any? %>
        (Average: <%= star_average(@post) %>)
      <% end %>
    </section>

  </div>

  <div id = 'comments'>
    <% @post.comments.each do |comment| %>
      <%= render '/comments/comment', { comment: comment } %>
    <% end %>
  </div>

  <%= render '/comments/form' %>
</div>