config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'auth/google_oauth2', as: :sign_in_with_google
  get 'auth/google_oauth2/callback' => 'callbacks#google'
  get 'auth/facebook', as: :sign_in_with_facebook
  get 'auth/facebook/callback' => 'callbacks#facebook'

    root 'home#index'
    get '/about' => 'home#about', as: :about
    resources :posts do
      resources :comments
      resources :favourites, only: [:create, :destroy]
      resources :stars, only: [:create, :update, :destroy]
    end
    resources :users do
      get :edit, on: :collection
      patch :update, on: :collection
    end
    resources :sessions, only: [:new, :create] do
      delete :destroy, on: :collection
    end
    resources :password_resets
    resources :tags, only: [:index, :show]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <navbar class="navbar">
      <div id='navbar-left'>
        <%= link_to 'Home', root_path %>
        <%= link_to 'About', about_path %>
        <%= link_to 'All Posts', posts_path %>
      </div>
      <div id='navbar-right'>
        <% if session[:user_id].present? %>
           Hi <%= "#{current_user.first_name}  " %>
           <%= link_to 'Favourites', users_path %>
           <%= link_to 'New Post', new_post_path %>
           <%= link_to 'Update User Info', edit_users_path%>
           <%= link_to 'Sign Out', sessions_path, method: :delete %>
        <% else %>
           <%= link_to 'Sign Up', new_user_path %>
           <%= link_to 'Sign In', new_session_path %>
         <% end %>
         <i class="fa fa-bars" aria-hidden="true"></i></label>
       </div>
    </navbar>

    <div class="responsive-menu">
        <ul>
          <% if session[:user_id].present? %>
            <li><%= link_to 'Update User Info', edit_users_path%></li>
            <li><%= link_to 'Sign Out', sessions_path, method: :delete %></li>
            <li><%= link_to 'Favourites', users_path %></li>
            <li><%= link_to 'New Post', new_post_path %></li>
          <% end %>
          <% if !session[:user_id].present? %>
            <li><%= link_to 'Sign Up', new_user_path %></li>
            <li><%= link_to 'Sign In', new_session_path %></li>
          <% end %>
        </ul>
     </div>

    <div class='main'>
      <% if alert || notice %>
        <div class='alert-notice'> <%= alert || notice %></div>
      <% end %>
      <%= yield %>
    </div>

  </body>
</html>